name: deploy-client-server-to-alwaysdata-action
run-name: ${{ github.actor }} DEPLOY GitHub Actions
on: [push]
jobs:
  deploy-client-server-to-alwaysdata-action:
    runs-on: ubuntu-latest
    steps:
    - name: install ssh
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo lol > connected_by_github_action && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
